config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'pages#home'
  get 'contact' => 'pages#contact'
   get 'about' => 'pages#about'

  resources :orders
  resources :farms do
    #post "/products/:id" => "products#add_to" , as: :add_product
    post "/products/:id/" => "products#order" , as: :order_product
    resources :products
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/farm.rb
# == Schema Information
#
# Table name: farms
#
#  id               :integer          not null, primary key
#  address          :string
#  title            :string
#  phone            :string
#  background_image :string
#  description      :text
#  open_hours       :text
#  orders_days      :text
#  delivery_days    :text
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

class Farm < ApplicationRecord

  has_many :products

  #address text
  #postalcode / zipcode string
  #city string

end

app/controllers/farms_controller.rb
class FarmsController < ApplicationController
  before_action :set_farm, only: [:show, :edit, :update, :destroy]

  # GET /farms
  # GET /farms.json
  def index
    @farms = Farm.all
  end

  # GET /farms/1
  # GET /farms/1.json
  def show
    @products = Product.all
    @farm_products = @farm.products(@farm.id).each
  end

  # GET /farms/new
  def new
    @farm = Farm.new
  end

  # GET /farms/1/edit
  def edit
  end

  # POST /farms
  # POST /farms.json
  def create
    @farm = Farm.new(farm_params)

    respond_to do |format|
      if @farm.save
        format.html { redirect_to @farm, notice: 'Farm was successfully created.' }
        format.json { render :show, status: :created, location: @farm }
      else
        format.html { render :new }
        format.json { render json: @farm.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /farms/1
  # PATCH/PUT /farms/1.json
  def update
    respond_to do |format|
      if @farm.update(farm_params)
        format.html { redirect_to @farm, notice: 'Farm was successfully updated.' }
        format.json { render :show, status: :ok, location: @farm }
      else
        format.html { render :edit }
        format.json { render json: @farm.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /farms/1
  # DELETE /farms/1.json
  def destroy
    @farm.destroy
    respond_to do |format|
      format.html { redirect_to farms_url, notice: 'Farm was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_farm
      @farm = Farm.find(params[:id])
      # redirect_to root_path if @farm.user != current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def farm_params
      #params.fetch(:farm, {:address,:title,:phone,:background_image,:description,:open_hours,:orders_days,:deliverys_days})
      params.require(:farm).permit(:address,:title,:phone,:background_image,:description,:open_hours,:orders_days,:deliverys_days )
    end
end

app/helpers/farms_helper.rb
module FarmsHelper
end

app/views/farms/_form.html.erb
<%= form_for(farm) do |f| %>
  <% if farm.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(farm.errors.count, "error") %> prohibited this farm from being saved:</h2>

      <ul>
      <% farm.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= simple_form_for @farm do |f| %>
      <%= f.input :title %>
      <%= f.input :background_image %>
      <%= f.input :address %>
      <%= f.input :phone %>
      <%= f.input :description %>
      <div class="actions">
        <%= f.submit %>
      </div>
  <% end %>
<% end %>

app/views/farms/edit.html.erb
<section class="banner shop" style="background-image: url(<%= @farm.background_image %>);">
    <div class="container">
        <div class="morepage-banner">
            <h2 class="title">Edition d'une ferme</h2>
        </div>
    </div>
</section>
<section class="container-padding">

<%= render 'form', farm: @farm %>

<%= link_to 'Show', @farm %> |
<%= link_to 'Back', farms_path %>
</section>

app/views/farms/index.html.erb
<section class="banner shop" style="background-image: url('http://i.imgur.com/qnH1Efi.jpg')" >
    <div class="container">
        <div class="morepage-banner">
            <h2 class="title">Les fermes</h2>
        </div>
    </div>
</section>
<section class="page-main padding-top-100 padding-bottom-100">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-xs-12 main-left">
            <div class="list-block column-1">
              <% @farms.each do |farm| %>
                <div class="item">
                    <div class="block-6">
                        <div class="block-image"><img src="<%=farm.background_image%>" alt="" class="img-full">
                            <%= link_to farm do%> <% end%>
                        </div>
                        <div class="block-content"><%= link_to farm.title, farm, class: "title"%>
                            <p class="description"><%= farm.address %><br><%= farm.phone %></p>
                            <ul class="list-icons">
                                <li><%= link_to edit_farm_path(farm), class: "link" do%><i class="icons fa fa-pencil"></i><% end%></li>
                                <li><%= link_to farm, method: :delete, data: { confirm: 'Vous êtes sûr ?' }, class: "link" do %><i class="icons fa fa-times"></i><% end%></li>
                            </ul>
                        </div>
                    </div>
                </div>
              <% end%>
            </div>
        </div>
    </div>
</div>
</section>
<br>

<%= link_to 'New Farm', new_farm_path %>

app/views/farms/new.html.erb
<section class="banner shop" style="background-image: url('http://i.imgur.com/qnH1Efi.jpg')">
    <div class="container">
        <div class="morepage-banner">
            <h2 class="title">Nouvelle ferme</h2>
        </div>
    </div>
</section>
<section class="container-padding">
<%= render 'form', farm: @farm %>

<%= link_to 'Back', farms_path %>
</section>

app/views/farms/show.html.erb
                    <section class="banner shop" style="background-image: url(<%= @farm.background_image %>);">
                        <div class="container">
                            <div class="morepage-banner">
                                <h2 class="title"><%= @farm.title %></h2>
                            </div>
                            <p><%= @farm.description%><p>
                            <p>Numéro de téléphone : <%= @farm.phone %></p>
                            <p>Adresse : <%= @farm.address %></p>
                        </div>
                    </section>
                    <section class="page-main padding-top-100">
                        <div class="container">
                            <div class="row">
                                <div class="list-block column-2">
                                    <% @farm.products(@farm.id).each do |product| %>
                                    <div class="item">
                                      <div class="block-4">
                                          <div class="block-image">><img width="358" src="<%= product.image %>" alt="Image de <%= product.name %>" class="img-full">
                                            <%= link_to farm_product_path(@farm, product), class: "link" do%><% end%>
                                          </div>
                                          <div class="block-content"><a href="<%= farm_product_path(@farm, product)%>" class="title"><%= product.name %></a>
                                            <div class="prices-wrapper">
                                                <div class="prices"><sup>€</sup><span class="number"><%= product.price %></span></div><span class="unit">/<%= product.unit %></span>
                                            </div>
                                                <ul class="list-icons">
                                                  <li><%= link_to farm_product_path(@farm, product), method: :delete, data: { confirm: "Voulez-vous vraiment supprimer ce produit ?" }, class: "link" do%> <i class="icons fa fa-times"></i> <%end%></li>
                                                  <li><%= link_to edit_farm_product_path(@farm, product), class: "link" do%> <i class="icons fa fa-pencil"></i> <%end%></li>
                                                  <li><%= link_to farm_product_path(@farm, product), class: "link" do%> <i class="icons fa fa-cart-plus"></i> <%end%></li>
                                                </ul>
                                            </div>
                                        </div>
                                        <p>
                                    </div>
                                    <%end%>
            <div id="back-top"><a href="#top" class="link"><i class="fa fa-angle-double-up"></i></a></div>
        </div>
        </div>
 <%= link_to 'Ajouter un produit', new_farm_product_path(@farm) %>
 <%= link_to 'Modifier la ferme', edit_farm_path(@farm) %>
 <%= link_to 'Retour', farms_path %>
    </body>
</html>