config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'pages#home'
  get 'contact' => 'pages#contact'
   get 'about' => 'pages#about'

  resources :orders
  resources :farms do
    #post "/products/:id" => "products#add_to" , as: :add_product
    post "/products/:id/" => "products#order" , as: :order_product
    resources :products
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id              :integer          not null, primary key
#  name            :text
#  image           :text
#  price           :float
#  unit            :string
#  available_in    :text
#  avalaible_stock :integer
#  real_stock      :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  farm_id         :integer
#

class Product < ApplicationRecord

  belongs_to :farm
  has_and_belongs_to_many :orders

  def to_s
    "#{name}"
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :set_farm
  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
    # @farm = @product.farm
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  def order
    if current_user.nil?
      redirect_to new_user_registration_path
    else
      @product = Product.find params[:id]
      @quantity = params[:quantity].to_i
      @order = current_user.add_to_order @product, @quantity
      redirect_to @order
    end
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @product.farm = @farm

    respond_to do |format|
      if @product.save
        format.html { redirect_to farm_path(@farm), notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to farm_path(@farm), notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to farm_path(@farm), notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    def set_farm
      @farm = Farm.find(params[:farm_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      #params.fetch(:product, {})
      params.require(:product).permit(:name,:image,:price,:unit,:available_in,:avalaible_stock,:real_stock,:farm_id )
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= simple_form_for [@farm, product] do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
    <% end %>
      <%= f.input :name %>
      <%= f.input :image %>
      <%= f.input :price %>
      <%= f.select :unit , [['Kilogrammes','Kg'],['Grammes','Gr'],['Par unité',"L'unité"]]%>
      <%= f.input :real_stock %>
      <div class="actions">
        <%= f.submit %>
      </div>
<% end %>

app/views/products/edit.html.erb
<section class="banner shop" style="background-image: url('http://i.imgur.com/428jSqD.jpg')"  >
    <div class="container">
        <div class="morepage-banner">
            <h2 class="title">Edition d'un produit</h2>
        </div>
    </div>
</section>
<%= render 'form', product: @product %>

<%= link_to 'Back', farm_path(@farm) %>

app/views/products/index.html.erb
<section class="banner shop" style="background-image: url('http://i.imgur.com/428jSqD.jpg')">
    <div class="container">
        <div class="morepage-banner">
            <h2 class="title">Produit</h2>
        </div>
    </div>
</section>

<table>
  <thead>
    <tr>
      <th>Nom du produit</th>
      <th>Image du produit</th>
      <th>Prix</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.image %></td>
        <td><%= product.price %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<section class="banner shop" style="background-image: url('http://i.imgur.com/428jSqD.jpg')">
    <div class="container">
        <div class="morepage-banner">
            <h2 class="title">Ajouter un produit</h2>
        </div>
    </div>
</section>
<%= render 'form', product: @product %>

<%= link_to 'Back', farm_path(@farm) %>

app/views/products/show.html.erb
<section class="banner shop" style="background-image: url('http://i.imgur.com/428jSqD.jpg')">
    <div class="container">
        <div class="morepage-banner">
            <h2 class="title">Le produit</h2>
        </div>
    </div>
</section>
<img width="500px" src="<%=@product.image%>" />
</div>
<%= form_tag(farm_order_product_path(@farm.id, @product.id), method: "post") do %>
  <%= label_tag(:quantity, "Quantité:") %>
  <%= number_field(nil, :quantity, value: 1) %>
  <%= @product.unit %>
  <%= submit_tag("Ajouter au panier") %>
<% end %>

 <%= link_to 'Edit', edit_farm_product_path(@product) %>
 <%= link_to 'Back', farm_products_path %>